#!/usr/bin/env python3
"""
Generate React config.js file from .env file.
This script reads the .env file and generates src/config.js with Firebase configuration.
"""
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Get Firebase config from environment variables
firebase_config = {
    'apiKey': os.environ.get('FIREBASE_API_KEY', ''),
    'authDomain': os.environ.get('FIREBASE_AUTH_DOMAIN', ''),
    'projectId': os.environ.get('FIREBASE_PROJECT_ID', ''),
    'storageBucket': os.environ.get('FIREBASE_STORAGE_BUCKET', ''),
    'messagingSenderId': os.environ.get('FIREBASE_MESSAGING_SENDER_ID', ''),
    'appId': os.environ.get('FIREBASE_APP_ID', ''),
    'measurementId': os.environ.get('FIREBASE_MEASUREMENT_ID', ''),
}

# Generate config.js content
config_js_content = """// Firebase Configuration
// This file is auto-generated from .env file using generate_config.py
// DO NOT edit this file manually - edit .env and regenerate instead

const firebaseConfig = {
  apiKey: "{apiKey}",
  authDomain: "{authDomain}",
  projectId: "{projectId}",
  storageBucket: "{storageBucket}",
  messagingSenderId: "{messagingSenderId}",
  appId: "{appId}",
  measurementId: "{measurementId}",
};

export default firebaseConfig;
""".format(**firebase_config)

# Write to src/config.js
config_path = os.path.join('src', 'config.js')
os.makedirs(os.path.dirname(config_path), exist_ok=True)

with open(config_path, 'w', encoding='utf-8') as f:
    f.write(config_js_content)

print(f"✅ Generated {config_path} from .env file")
print(f"   Firebase API Key: {firebase_config['apiKey'][:20]}...")
print(f"   Firebase Project ID: {firebase_config['projectId']}")

